apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: hamzabelmo/devops_project2:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "172.17.0.2"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "hamza"
        - name: MYSQL_DB
          value: "DevOpsProject2"