name: Deploy to Docker Hub

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t hamzabelmo/devops_project2:latest .
        
      - name: Tag Docker image
        run: docker tag hamzabelmo/devops_project2:latest hamzabelmo/devops_project2:v1 
        
      - name: Push Docker image
        run: docker push hamzabelmo/devops_project2:v1 